value = float(input("Enter the value: "))
print("price 0,1 kg candy: ",float(value*0.1))
print("price 0,2 kg candy: ",float(value*0.2))
print("price 0,3 kg candy: ",float(value*0.3))
print("price 0,4 kg candy: ",float(value*0.4))
print("price 0,5 kg candy: ",float(value*0.5))
print("price 0,6 kg candy: ",float(value*0.6))
print("price 0,7 kg candy: ",float(value*0.7))
print("price 0,8 kg candy: ",float(value*0.8))
print("price 0,9 kg candy: ",float(value*0.9))
print("price 1 kg candy: ", value)